### ISSUE TITLE
Updates to Oncotree NCI/UMLS Mappings

### ISSUE THREAD

**Issue by n1zea144** [cBioPortal/oncotree#203]
We want start using our own manually curated NCI/UMLs mappings.   With this in mind, we would like to:

- Disconnect integration with MSK crosswalk
- Inject our mapping files into the Oncotree backend for visualization on the website as is currently supported.

**Comment by sheridancbio** [comment]
The disconnection of crosswalk is now complete.

@ritikakundra : the current NCI/UMLS mappings for oncotree come from this static resource file:
https://github.com/cBioPortal/oncotree/blob/master/core/src/main/resources/staticCrosswalkOncotreeMappings.txt

If there are updated NCI/UMLS mappings, they can be incorporated by making a PR to update that file. Format:
first column: oncotree code
second column: comma separated list of NCI codes
third column comma separated list of UMLS codes

Aside from tab delimiter, no other spaces should be present.
