### ISSUE TITLE
Endometrioid Carcinoma (CEEN) should be renamed

### ISSUE THREAD

**Issue by j-hudecek** [cBioPortal/oncotree#21]
We think a better name for Endometrioid Carcinoma (CEEN) would be Cervical Endometrioid Carcinoma (CEEN) as the endometrioid carcinoma can happen in other places (for example Uterine Endometrioid Carcinoma (UEC)). On the other hand it is linked (in https://github.com/cBioPortal/oncotree/blob/master/tumor_tree.txt) to C3769 NCIt which can occur in other locations. So, either that will have to be changed, too – CEEN should represent the combination of topology and morphology, right? Or the fix is to move it out of Cervix to be in line with NCIt?

**Comment by zhx828** [comment]
@j-hudecek would you mind telling me your email address? I want to forward your issue to OncoTree committee. Thank you.

**Comment by j-hudecek** [comment]
j.hudecek@nki.nl
