### ISSUE TITLE
Include OncoTree paper on the website 

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/oncotree#237]
Should we include the OncoTree paper on the main website, similar to OncoKB?

When using OncoTree, please cite: [Kundra et al., JCO Clinical Cancer Informatics 2021](https://ascopubs.org/doi/10.1200/CCI.20.00108).

**Comment by jjgao** [comment]
Good idea!

**Comment by sheridancbio** [comment]
@ritikakundra : the content of the oncotree main page begins in file web/src/main/resources/static/index.html ... for instance the bottom text "website questions: <link>" is in this file.
There are other scripts which populate content in the document model. For example, the content of the elements "oncotree-version-label" "oncotree-version-statistics" and "oncotree-version-note" is populated when this script runs: 
web/src/main/resources/static/js/main.js
(see function initVersionsLink())

**Comment by zhx828** [comment]
The paper link has been added in https://github.com/cBioPortal/oncotree/commit/263bbfadc37926a64b0a2aa2ea022fe7e99cc561
