### ISSUE TITLE
API down or not operational?

### ISSUE THREAD

**Issue by sigven** [cBioPortal/oncotree#265]
Hi,

I am struggling to query the API currently (here using R):

```
ot_tumor_types_tree <-  jsonlite::fromJSON("http://oncotree.mskcc.org/api/tumorTypes/tree")
Error in open.connection(con, "rb") : 
  cannot open the connection to 'http://oncotree.mskcc.org/api/tumorTypes/tree'
In addition: Warning message:
In open.connection(con, "rb") :
  cannot open URL 'http://oncotree.mskcc.org/api/tumorTypes/tree': HTTP status was '403 Forbidden'
```

This usually works nicely.

kind regards,
Sigve

**Comment by sheridancbio** [comment]
@sigven I just tried hitting http://oncotree.mskcc.org/api/tumorTypes/tree and it worked fine for me.

However, if anyone is having trouble with this URL I suggest you switch to the canonical host name for oncotree, which was changed to "oncotree.info" several years back.

The name "oncotree.mskcc.org" may still be supported, but the legacy rules in our proxy / ingress / loadbalancer sometimes break down and it may take time for us to look into it. It would probably be better for us to announce a date after which "oncotree.mskcc.org" will no longer function. But I would suggest to anyone still using "oncotree.mskcc.org" to consider that host name as no longer supported.

If switching to "oncotree.info" helps you @sigven, please post back to this issue. Thanks

**Comment by sigven** [comment]
Hi @sheridancbio,

Thanks a lot for your comment. I was not aware of the `oncotree.info` URL; that made it work right away. I've had the same URL for several years, which is now outdated, thanks updating me on this.

All works fine now, the JSON can be parsed instantly. I'll close this issue as resolved.

Thanks!

best,
Sigve

**Comment by sheridancbio** [comment]
That's great ... I'm glad that solved your difficulty, and thank you for letting us know that it worked. 👍
