### ISSUE TITLE
Oncotree node "TISSUE" .. is it valid? Does it have a defined color?

### ISSUE THREAD

**Issue by sheridancbio** [cBioPortal/oncotree#43]
Currently we have a node in our vocabulary for "TISSUE", and it is returned from the oncotree web api. Is this a valid code? It should have a row of its own in the table if so .. and should probably have a color defined .. on the oncotree website it appears white.

**Comment by ritikakundra** [comment]
@sheridancbio I dont think this will ever be a cancer type assignment.It should never be.
